<?xml version="1.0"?>
<robot name="ALEX" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="base_offset_x" value="0" />
  <xacro:property name="base_offset_y" value="0" />
  <xacro:property name="base_offset_z" value="0" />
  <xacro:property name="hip_offset_x" value="0.1" />
  <xacro:property name="hip_offset_y" value="0.1" />
  <xacro:property name="hip_offset_z" value="0.1" />
  <xacro:property name="hip_length" value="0" />
  <xacro:property name="knee_length_a" value="0.1" />
  <xacro:property name="knee_length_b" value="0.3" />
  <xacro:property name="shin_length_a" value="0.309" />
  <xacro:property name="shin_length_b" value="0.305" />
  <xacro:property name="shin_connection_length" value="0.115" />
  <xacro:property name="ankle_a_offset" value="0.07475" />
  <xacro:property name="ankle_length_b" value="0.02735" />
  <xacro:property name="ankle_length_c" value="0.0432" />
  <xacro:property name="ankle_length_d1" value="0.1493" />
  <xacro:property name="ankle_length_d2" value="0.155795" />
  <xacro:property name="foot_length_a" value="0.055" />
  <xacro:property name="foot_length_b" value="0.055" />

  <xacro:property name="l1" value="0.1" />
  <xacro:property name="l2" value="0.3" />
  <xacro:property name="l3" value="0.309" />
  <xacro:property name="l4" value="0.115" />
  <xacro:property name="l5" value="0.19" />
  <xacro:property name="l6" value="0.02735" />
  <xacro:property name="l7" value="0.0432" />
  <xacro:property name="l8_a" value="0.1493" />
  <xacro:property name="l8_b" value="0.155795" />
  <xacro:property name="l9" value="0.055" />
  <xacro:property name="l10" value="0.04025" />
  <xacro:property name="l11" value="0.07475" />

  <xacro:property name="pi" value="3.1415926535897932384626433832795" />

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>

  <material name="yellow">
    <color rgba="1 1 0 1"/>
  </material>

  <material name="silver">
    <color rgba="0.73 0.73 0.73 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <link name="base_link">
    <visual>
      <material name="yellow"/>
    </visual>
  </link>

  <link name="hip_link">
    <visual>
      <geometry>
        <cylinder length="${knee_length_a}" radius="0.003"/>
      </geometry>
    </visual>
  </link>
  <joint name="base_link_to_hip_link" type="continuous">
    <parent link="base_link"/>
    <child link="hip_link"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 ${pi/2} ${pi}" xyz="0 0 0"/>
  </joint>

  <link name="knee_link_b">
    <visual>
      <geometry>
        <cylinder length="${knee_length_b}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${knee_length_b/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="hip_link_to_knee_link_b" type="continuous">
    <parent link="hip_link"/>
    <child link="knee_link_b"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="${pi/2} ${-pi/4} 0" xyz="${hip_offset_x} ${hip_offset_y} ${hip_offset_z}"/>
  </joint>

  <link name="shin_link_b">
    <visual>
      <geometry>
        <cylinder length="${shin_length_b}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${shin_length_b/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="knee_link_b_to_shin_link_b" type="continuous">
    <parent link="knee_link_b"/>
    <child link="shin_link_b"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 0 ${-pi/2}" xyz="${knee_length_b} 0 0"/>
  </joint>

  <link name="knee_link_a">
    <visual>
      <geometry>
        <cylinder length="${knee_length_a}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${knee_length_a/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="knee_link_b_to_knee_link_a" type="continuous">
    <parent link="knee_link_b"/>
    <child link="knee_link_a"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 0 ${-pi/2}" xyz="0 0 0"/>
  </joint>

  <link name="shin_link_a">
    <visual>
      <geometry>
        <cylinder length="${shin_length_a}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${shin_length_a/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="knee_link_a_to_shin_link_a" type="continuous">
    <parent link="knee_link_a"/>
    <child link="shin_link_a"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 0 ${pi/2}" xyz="${knee_length_a} 0 0"/>
  </joint>

  <link name="shin_link_connection">
    <visual>
      <geometry>
        <cylinder length="0" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${shin_connection_length/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="shink_link_b_to_shin_link_connection" type="continuous">
    <parent link="shin_link_b"/>
    <child link="shin_link_connection"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="${shin_connection_length} 0 0"/>
  </joint>

  <link name="ankle_link_a">
    <visual>
      <geometry>
        <cylinder length="${ankle_length_b}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${ankle_length_b/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="shin_link_b_to_ankle_link_a" type="continuous">
    <parent link="shin_link_b"/>
    <child link="ankle_link_a"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 0 ${pi/2}" xyz="${ankle_a_offset} 0 0"/>
  </joint>

  <link name="ankle_link_b">
    <visual>
      <geometry>
        <cylinder length="${ankle_length_c}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${ankle_length_c/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="ankle_link_a_to_ankle_link_b" type="continuous">
    <parent link="ankle_link_a"/>
    <child link="ankle_link_b"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 0 ${-pi/8}" xyz="${ankle_length_b} 0 0"/>
  </joint>

  <link name="ankle_link_c_1">
    <visual>
      <geometry>
        <cylinder length="${ankle_length_d1}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${ankle_length_d1/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="ankle_link_b_to_ankle_link_c_1" type="continuous">
    <parent link="ankle_link_b"/>
    <child link="ankle_link_c_1"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 0 ${-pi/4}" xyz="${ankle_length_c} 0 0"/>
  </joint>

  <link name="ankle_link_c_2">
    <visual>
      <geometry>
        <cylinder length="${ankle_length_d2}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${ankle_length_d2/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="ankle_link_c_1_to_ankle_link_c_2" type="prismatic">
    <limit lower="${-ankle_length_d1/2}" upper="${ankle_length_d1/2}" effort="1" velocity="1"/>
    <parent link="ankle_link_c_1"/>
    <child link="ankle_link_c_2"/>
    <axis rpy="0 0 0" xyz="1 0 0"/>
    <origin rpy="0 0 0" xyz="${ankle_length_d1} 0 0"/>
  </joint>

  <link name="foot_link_a">
    <visual>
      <geometry>
        <cylinder length="${foot_length_a}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${foot_length_a/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="ankle_link_c_2_to_foot_link_a" type="continuous">
    <parent link="ankle_link_c_2"/>
    <child link="foot_link_a"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 0 ${-pi/2}" xyz="${ankle_length_d2} 0 0"/>
  </joint>

  <link name="foot_link_b">
    <visual>
      <geometry>
        <cylinder length="${foot_length_b}" radius="0.003"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${foot_length_b/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  <joint name="foot_link_a_to_foot_link_b" type="continuous">
    <parent link="foot_link_a"/>
    <child link="foot_link_b"/>
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="${foot_length_a} 0 0"/>
  </joint>



</robot>
