legs: {
  leftLeg:  { Enabled: true,
              M1Enabled: true,
              M2Enabled: true,
              M3Enabled: true,
              M1ID: 3,
              M2ID: 4,
              M3ID: 1
              },
  rightLeg: { Enabled: false,
              M1Enabled: true,
              M2Enabled: true,
              M3Enabled: true,
              M1ID: 5,
              M2ID: 6,
              M3ID: 2
              },
  limbLengthsSS: { o_base_to_hip_x: 0,
                 o_base_to_hip_y: -0.5,
                 o_base_to_hip_z: -0.1,
                 o_hip_to_knee_x: 0.1,
                 o_hip_to_knee_y: 0.1,
                 o_hip_to_knee_z: 0.1,
                 l_knee_a: 0.1,
                 l_knee_b: 0.3,
                 l_shin_a: 0.309,
                 l_shin_b: 0.305,
                 l_shin_connection: 0.115,
                 l_ankle_connection: 0.07475,
                 l_ankle_a: 0.02735,
                 l_ankle_b: 0.0432,
                 l_ankle_c1: 0.1493,
                 l_ankle_c2: 0.155795,
                 l_foot_a: 0.055,
                 l_foot_b: 0.055
                 },
                 # Robot base link connects to leg hip link - this is not a visible joint, this symbolic joint located in the mirrored servo rotor position
                 # This symbolic joint is parent to motor rotor as well as hip tilt joint
                 # Base linke has x forward, z up, y left
                 # All lengths/offsets are in reference to left leg - hip must be mirrored for right leg
                 # Offsets axes are global axes ie offset_x is an offset in the base_link x axis, not the specific tf x axis

    limbLengthsSSS: {
                    # Base link to coronal hip
                    l_base_to_sybolic_hip_yz: 0.101366, #Probably wont use
                    o_base_to_symbolic_hip_y: 0.084011,
                    o_base_to_symbolic_hip_z: -0.056722,
                    a_base_to_symbolic_hip: 145.974,

                    # Coronal Hip
                    # Side to side hip movement
                    l_symbolic_hip_to_coronal_hip_rotor: 0.0338,
                    l_coronal_hip_torque_arm: 0.046803,
                    l_coronal_hip_torque_arm_to_coronal_hip_push_point: 0.043656,
                    l_coronal_hip_push_point_to_coronal_hip_pivot: 0.067801,
                    l_symbolic_hip_to_coronal_hip_pivot: 0.068139,
                    o_symbolic_hip_to_coronal_hip_pivot_z: -0.066081,
                    o_symbolic_hip_to_coronal_hip_pivot_y: 0.01619,
                    l_coronal_hip_pivot_to_sagittal_hip_pivot: 0.059613, #Probably wont use
                    o_coronal_hip_pivot_to_sagittal_hip_pivot_y: 0.0025,
                    o_coronal_hip_pivot_to_sagittal_hip_pivot_z: -0.059561,

                    # Sagittal Hip
                    # Forward to back hip movement
                    a_coronal_hip_pivot_to_sagital_hip_pivot: 0.3370928917,
                    l_thigh_a: 0.100,
                    l_thigh_b: 0.300, # This is currently wrong due to slight misaignment in model
                    l_shin_a: 0.3206,
                    l_shin_b: 0.275,
                    l_knee_b_to_ankle_connection: 0.07475,
                    l_knee_b_to_shin_connection: 0.070,

                    # Ankle
                    l_ankle_connection_to_ankle_rotor: 0.02735,
                    l_ankle_torque_arm: 0.0432,
                    l_ankle_linear_actuator_a: 0.1493,
                    l_ankle_linear_actuator_b: 0.155795,
                    l_linear_actuator_b_to_shin_b: 0.055
                  },
      hipLengths: {
                  L1: 0.05996,
                  L2: 0.0338,
                  L3: 0.046803,
                  L4: 0.043656,
                  L5: 0.067801,
                  L6: 0.068139,
                  L7: 0.059961
                  },
      hipSigma: {
                S0: 149.22,
                S1: 134.896,
                S2: 75.884,
                S3: 109.314,
                S4: 149.22,
                S5: 75.425,
                S6: 28.691,
                S7: 104.574,
                S8: 75.884
                },
      lowerLegLengths_Actual: { #Actual Lengths
                        L1: 0.1,
                        L2: 0.31,
                        L3: 0.315,
                        L4: 0.105,
                        L5: 0.17
                        },
      lowerLegLengths_CAD: { #Actual Lengths
                        L1: 0.1,
                        L2: 0.296102,
                        L3: 0.3206,
                        L4: 0.07,
                        L5: 0.205
                        }
}

comms: {
  RS485: { BaudRate: 57600,
           DeviceName: "/dev/ttyUSB0",
           ProtocolVersion: 2.0
          },
  CAN: {

        }
}

AK80-9: {
  P_MIN: -12.5,
  P_MAX: 12.5,
  V_MIN: -45.0,
  V_MAX: 45.0,
  KP_MIN: 0.0,
  KP_MAX: 500.0,
  KD_MIN: 0.0,
  KD_MAX: 5.0,
  T_MIN: -18.0,
  T_MAX: 18.0
  }

system: { UseMPU6050: true,
          UseORIENTUS: false,
          port: "/dev/ttyACM0",
          UseRVIZ: true,
          UseFKINEGUI: true,
          UseIKINEGUI: false,
          PublishFrequency: 30,
          UseCADLengths: false
         }

tests: { HopTestEnabled: false,
         WalkGaitEnabled: false,
         LegTeleopEnabled: false,


        }
